plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fissure.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.fissure.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "2.0.0"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.webkit:webkit:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
